"""
300+ progressive / left-wing news sources worldwide.
Each entry: (name, feed_url, website, language, country)
Feed URLs use common RSS patterns; the crawler auto-discovers if a feed 404s.
"""

SOURCES: list[tuple[str, str, str, str, str]] = [
    # ── USA ──────────────────────────────────────────────────────────────
    ("Democracy Now!", "https://www.democracynow.org/democracynow.rss", "https://www.democracynow.org", "en", "US"),
    ("The Intercept", "https://theintercept.com/feed/?rss", "https://theintercept.com", "en", "US"),
    ("Mother Jones", "https://www.motherjones.com/feed/", "https://www.motherjones.com", "en", "US"),
    ("The Nation", "https://www.thenation.com/feed/", "https://www.thenation.com", "en", "US"),
    ("Jacobin", "https://jacobin.com/feed/", "https://jacobin.com", "en", "US"),
    ("Common Dreams", "https://www.commondreams.org/feeds/all", "https://www.commondreams.org", "en", "US"),
    ("Truthout", "https://truthout.org/feed/", "https://truthout.org", "en", "US"),
    ("In These Times", "https://inthesetimes.com/feed", "https://inthesetimes.com", "en", "US"),
    ("The Progressive", "https://progressive.org/feed/", "https://progressive.org", "en", "US"),
    ("CounterPunch", "https://www.counterpunch.org/feed/", "https://www.counterpunch.org", "en", "US"),
    ("Salon", "https://www.salon.com/feed/", "https://www.salon.com", "en", "US"),
    ("AlterNet", "https://www.alternet.org/feed/", "https://www.alternet.org", "en", "US"),
    ("Raw Story", "https://www.rawstory.com/feed/", "https://www.rawstory.com", "en", "US"),
    ("Daily Kos", "https://www.dailykos.com/blogs/main.rss", "https://www.dailykos.com", "en", "US"),
    ("HuffPost", "https://www.huffpost.com/section/front-page/feed", "https://www.huffpost.com", "en", "US"),
    ("Vox", "https://www.vox.com/rss/index.xml", "https://www.vox.com", "en", "US"),
    ("MSNBC", "https://www.msnbc.com/feeds/latest", "https://www.msnbc.com", "en", "US"),
    ("Slate", "https://slate.com/feeds/all.rss", "https://slate.com", "en", "US"),
    ("The American Prospect", "https://prospect.org/feed/", "https://prospect.org", "en", "US"),
    ("Dissent Magazine", "https://www.dissentmagazine.org/feed/", "https://www.dissentmagazine.org", "en", "US"),
    ("Current Affairs", "https://www.currentaffairs.org/feed/", "https://www.currentaffairs.org", "en", "US"),
    ("Truthdig", "https://www.truthdig.com/feed/", "https://www.truthdig.com", "en", "US"),
    ("The Real News", "https://therealnews.com/feed", "https://therealnews.com", "en", "US"),
    ("People's World", "https://www.peoplesworld.org/feed/", "https://www.peoplesworld.org", "en", "US"),
    ("Liberation News", "https://www.liberationnews.org/feed/", "https://www.liberationnews.org", "en", "US"),
    ("Socialist Worker", "https://socialistworker.org/feed/", "https://socialistworker.org", "en", "US"),
    ("Left Voice", "https://www.leftvoice.org/feed/", "https://www.leftvoice.org", "en", "US"),
    ("Portside", "https://portside.org/rss.xml", "https://portside.org", "en", "US"),
    ("Fairness & Accuracy In Reporting", "https://fair.org/feed/", "https://fair.org", "en", "US"),
    ("The Lever", "https://www.levernews.com/rss/", "https://www.levernews.com", "en", "US"),
    ("ProPublica", "https://feeds.propublica.org/propublica/main", "https://www.propublica.org", "en", "US"),
    ("The Marshall Project", "https://www.themarshallproject.org/rss/all", "https://www.themarshallproject.org", "en", "US"),
    ("Splinter News", "https://splinternews.com/rss", "https://splinternews.com", "en", "US"),
    ("Talking Points Memo", "https://talkingpointsmemo.com/feed/all", "https://talkingpointsmemo.com", "en", "US"),
    ("Crooks and Liars", "https://crooksandliars.com/feeds/all", "https://crooksandliars.com", "en", "US"),
    ("Wonkette", "https://www.wonkette.com/feed", "https://www.wonkette.com", "en", "US"),
    ("The Root", "https://www.theroot.com/rss", "https://www.theroot.com", "en", "US"),
    ("Rewire News Group", "https://rewirenewsgroup.com/feed/", "https://rewirenewsgroup.com", "en", "US"),
    ("Grist", "https://grist.org/feed/", "https://grist.org", "en", "US"),
    ("The Revelator", "https://therevelator.org/feed/", "https://therevelator.org", "en", "US"),
    ("Inequality.org", "https://inequality.org/feed/", "https://inequality.org", "en", "US"),
    ("EcoWatch", "https://www.ecowatch.com/rss", "https://www.ecowatch.com", "en", "US"),
    ("Labor Notes", "https://labornotes.org/rss.xml", "https://labornotes.org", "en", "US"),
    ("Strikewave", "https://www.strikewave.co.uk/feed", "https://www.strikewave.co.uk", "en", "US"),
    ("Teen Vogue (politics)", "https://www.teenvogue.com/feed/rss", "https://www.teenvogue.com", "en", "US"),
    ("The Baffler", "https://thebaffler.com/feed", "https://thebaffler.com", "en", "US"),
    ("n+1", "https://www.nplusonemag.com/feed/", "https://www.nplusonemag.com", "en", "US"),
    ("Boston Review", "https://www.bostonreview.net/feed/", "https://www.bostonreview.net", "en", "US"),
    ("Mondoweiss", "https://mondoweiss.net/feed/", "https://mondoweiss.net", "en", "US"),
    ("The Electronic Intifada", "https://electronicintifada.net/rss.xml", "https://electronicintifada.net", "en", "US"),

    # ── UK & Ireland ─────────────────────────────────────────────────────
    ("The Guardian", "https://www.theguardian.com/world/rss", "https://www.theguardian.com", "en", "UK"),
    ("The Guardian Opinion", "https://www.theguardian.com/commentisfree/rss", "https://www.theguardian.com/commentisfree", "en", "UK"),
    ("Morning Star", "https://morningstaronline.co.uk/feed", "https://morningstaronline.co.uk", "en", "UK"),
    ("Tribune Magazine", "https://tribunemag.co.uk/feed/", "https://tribunemag.co.uk", "en", "UK"),
    ("Novara Media", "https://novaramedia.com/feed/", "https://novaramedia.com", "en", "UK"),
    ("The Canary", "https://www.thecanary.co/feed/", "https://www.thecanary.co", "en", "UK"),
    ("Byline Times", "https://bylinetimes.com/feed/", "https://bylinetimes.com", "en", "UK"),
    ("openDemocracy", "https://www.opendemocracy.net/en/rss/", "https://www.opendemocracy.net", "en", "UK"),
    ("Red Pepper", "https://www.redpepper.org.uk/feed/", "https://www.redpepper.org.uk", "en", "UK"),
    ("New Statesman", "https://www.newstatesman.com/feed", "https://www.newstatesman.com", "en", "UK"),
    ("The London Economic", "https://www.thelondoneconomic.com/feed/", "https://www.thelondoneconomic.com", "en", "UK"),
    ("Prospect Magazine", "https://www.prospectmagazine.co.uk/feed", "https://www.prospectmagazine.co.uk", "en", "UK"),
    ("The Independent (Voices)", "https://www.independent.co.uk/voices/rss", "https://www.independent.co.uk", "en", "UK"),
    ("New Left Review", "https://newleftreview.org/feed", "https://newleftreview.org", "en", "UK"),
    ("Socialist Worker UK", "https://socialistworker.co.uk/feed/", "https://socialistworker.co.uk", "en", "UK"),
    ("Weekly Worker", "https://weeklyworker.co.uk/feed/", "https://weeklyworker.co.uk", "en", "UK"),
    ("The Conversation UK", "https://theconversation.com/uk/articles.atom", "https://theconversation.com/uk", "en", "UK"),
    ("Bella Caledonia", "https://bellacaledonia.org.uk/feed/", "https://bellacaledonia.org.uk", "en", "UK"),
    ("CommonSpace", "https://www.commonspace.scot/rss", "https://www.commonspace.scot", "en", "UK"),
    ("The Journal.ie", "https://www.thejournal.ie/feed/", "https://www.thejournal.ie", "en", "IE"),
    ("Village Magazine", "https://villagemagazine.ie/feed/", "https://villagemagazine.ie", "en", "IE"),

    # ── France ───────────────────────────────────────────────────────────
    ("Mediapart", "https://www.mediapart.fr/articles/feed", "https://www.mediapart.fr", "fr", "FR"),
    ("Le Monde Diplomatique", "https://www.monde-diplomatique.fr/recents.xml", "https://www.monde-diplomatique.fr", "fr", "FR"),
    ("L'Humanité", "https://www.humanite.fr/rss/actu.rss", "https://www.humanite.fr", "fr", "FR"),
    ("Libération", "https://www.liberation.fr/rss/", "https://www.liberation.fr", "fr", "FR"),
    ("Politis", "https://www.politis.fr/feed/", "https://www.politis.fr", "fr", "FR"),
    ("Regards", "https://regards.fr/feed/", "https://regards.fr", "fr", "FR"),
    ("Reporterre", "https://reporterre.net/spip.php?page=backend", "https://reporterre.net", "fr", "FR"),
    ("Basta!", "https://basta.media/spip.php?page=backend", "https://basta.media", "fr", "FR"),
    ("Alternatives Économiques", "https://www.alternatives-economiques.fr/rss.xml", "https://www.alternatives-economiques.fr", "fr", "FR"),
    ("Le Vent Se Lève", "https://lvsl.fr/feed/", "https://lvsl.fr", "fr", "FR"),
    ("Ballast", "https://www.revue-ballast.fr/feed/", "https://www.revue-ballast.fr", "fr", "FR"),
    ("Contretemps", "https://www.contretemps.eu/feed/", "https://www.contretemps.eu", "fr", "FR"),
    ("Révolution Permanente", "https://www.revolutionpermanente.fr/feed", "https://www.revolutionpermanente.fr", "fr", "FR"),
    ("NPA", "https://www.anti-k.org/feed/", "https://www.anti-k.org", "fr", "FR"),
    ("Frustration Magazine", "https://www.frustrationmagazine.fr/feed/", "https://www.frustrationmagazine.fr", "fr", "FR"),

    # ── Germany ──────────────────────────────────────────────────────────
    ("taz", "https://taz.de/!p4608;rss/", "https://taz.de", "de", "DE"),
    ("Der Freitag", "https://www.freitag.de/@@RSS", "https://www.freitag.de", "de", "DE"),
    ("Jacobin DE", "https://jacobin.de/feed/", "https://jacobin.de", "de", "DE"),
    ("Neues Deutschland", "https://www.nd-aktuell.de/rss/alle-artikel", "https://www.nd-aktuell.de", "de", "DE"),
    ("Analyse & Kritik", "https://www.akweb.de/feed/", "https://www.akweb.de", "de", "DE"),
    ("junge Welt", "https://www.jungewelt.de/rss/inhalt.rss", "https://www.jungewelt.de", "de", "DE"),
    ("Telepolis", "https://www.telepolis.de/rss/news-atom.xml", "https://www.telepolis.de", "de", "DE"),
    ("Marx21", "https://www.marx21.de/feed/", "https://www.marx21.de", "de", "DE"),
    ("Sozialismus.info", "https://www.sozialismus.info/feed/", "https://www.sozialismus.info", "de", "DE"),
    ("Die Linke", "https://www.die-linke.de/feed/", "https://www.die-linke.de", "de", "DE"),
    ("Nachdenkseiten", "https://www.nachdenkseiten.de/?feed=rss2", "https://www.nachdenkseiten.de", "de", "DE"),
    ("Kontext Wochenzeitung", "https://www.kontextwochenzeitung.de/feed", "https://www.kontextwochenzeitung.de", "de", "DE"),

    # ── Spain ────────────────────────────────────────────────────────────
    ("elDiario.es", "https://www.eldiario.es/rss/", "https://www.eldiario.es", "es", "ES"),
    ("Público", "https://www.publico.es/rss/", "https://www.publico.es", "es", "ES"),
    ("La Marea", "https://www.lamarea.com/feed/", "https://www.lamarea.com", "es", "ES"),
    ("CTXT", "https://ctxt.es/es/rss/ctxt.xml", "https://ctxt.es", "es", "ES"),
    ("El Salto", "https://www.elsaltodiario.com/rss", "https://www.elsaltodiario.com", "es", "ES"),
    ("Rebelión", "https://rebelion.org/feed/", "https://rebelion.org", "es", "ES"),
    ("Diagonal", "https://www.diagonalperiodico.net/feed", "https://www.diagonalperiodico.net", "es", "ES"),
    ("Ara.cat", "https://www.ara.cat/rss/", "https://www.ara.cat", "ca", "ES"),
    ("VilaWeb", "https://www.vilaweb.cat/rss/", "https://www.vilaweb.cat", "ca", "ES"),
    ("Naiz", "https://www.naiz.eus/en/rss/", "https://www.naiz.eus", "eu", "ES"),
    ("Mundo Obrero", "https://www.mundoobrero.es/feed/", "https://www.mundoobrero.es", "es", "ES"),
    ("Kaos en la Red", "https://kaosenlared.net/feed/", "https://kaosenlared.net", "es", "ES"),

    # ── Italy ────────────────────────────────────────────────────────────
    ("il manifesto", "https://ilmanifesto.it/feed/", "https://ilmanifesto.it", "it", "IT"),
    ("Internazionale", "https://www.internazionale.it/feed", "https://www.internazionale.it", "it", "IT"),
    ("Il Fatto Quotidiano", "https://www.ilfattoquotidiano.it/feed/", "https://www.ilfattoquotidiano.it", "it", "IT"),
    ("Jacobin Italia", "https://jacobinitalia.it/feed/", "https://jacobinitalia.it", "it", "IT"),
    ("Dinamo Press", "https://www.dinamopress.it/feed/", "https://www.dinamopress.it", "it", "IT"),
    ("Collettiva", "https://www.collettiva.it/rss", "https://www.collettiva.it", "it", "IT"),
    ("Left", "https://left.it/feed/", "https://left.it", "it", "IT"),
    ("MicroMega", "https://www.micromega.net/feed/", "https://www.micromega.net", "it", "IT"),
    ("Global Project", "https://www.globalproject.info/it/feed", "https://www.globalproject.info", "it", "IT"),
    ("Contropiano", "https://contropiano.org/feed", "https://contropiano.org", "it", "IT"),

    # ── Portugal ──────────────────────────────────────────────────────────
    ("Esquerda.net", "https://www.esquerda.net/rss.xml", "https://www.esquerda.net", "pt", "PT"),
    ("Público PT", "https://feeds.feedburner.com/PublicoPT", "https://www.publico.pt", "pt", "PT"),
    ("Jornal Tornado", "https://jornaltornado.pt/feed/", "https://jornaltornado.pt", "pt", "PT"),
    ("O Diabo", "https://odiabo.pt/feed/", "https://odiabo.pt", "pt", "PT"),
    ("Setenta e Quatro", "https://setentaequatro.pt/feed", "https://setentaequatro.pt", "pt", "PT"),

    # ── Netherlands & Belgium ─────────────────────────────────────────────
    ("De Correspondent", "https://decorrespondent.nl/feed", "https://decorrespondent.nl", "nl", "NL"),
    ("Solidariteit", "https://www.solidariteit.nl/feed/", "https://www.solidariteit.nl", "nl", "NL"),
    ("Grenzeloos", "https://grenzeloos.org/feed/", "https://grenzeloos.org", "nl", "NL"),
    ("DeWereldMorgen", "https://www.dewereldmorgen.be/feed/", "https://www.dewereldmorgen.be", "nl", "BE"),
    ("Apache", "https://www.apache.be/feed/", "https://www.apache.be", "nl", "BE"),
    ("MO*", "https://www.mo.be/rss", "https://www.mo.be", "nl", "BE"),

    # ── Scandinavia ──────────────────────────────────────────────────────
    ("Klassekampen", "https://klassekampen.no/rss", "https://klassekampen.no", "no", "NO"),
    ("Radikal Portal", "https://radikalportal.no/feed/", "https://radikalportal.no", "no", "NO"),
    ("Flamman", "https://www.flamman.se/feed/", "https://www.flamman.se", "sv", "SE"),
    ("ETC", "https://www.etc.se/rss.xml", "https://www.etc.se", "sv", "SE"),
    ("Internationalen", "https://www.internationalen.se/feed/", "https://www.internationalen.se", "sv", "SE"),
    ("Arbetet", "https://arbetet.se/feed/", "https://arbetet.se", "sv", "SE"),
    ("Information", "https://www.information.dk/rss", "https://www.information.dk", "da", "DK"),
    ("Modkraft", "https://modkraft.dk/feed", "https://modkraft.dk", "da", "DK"),
    ("Enhedslisten", "https://enhedslisten.dk/feed", "https://enhedslisten.dk", "da", "DK"),
    ("Kansan Uutiset", "https://www.kansanuutiset.fi/feed/", "https://www.kansanuutiset.fi", "fi", "FI"),
    ("Voima", "https://voima.fi/feed/", "https://voima.fi", "fi", "FI"),

    # ── Greece ───────────────────────────────────────────────────────────
    ("Efsyn", "https://www.efsyn.gr/rss.xml", "https://www.efsyn.gr", "el", "GR"),
    ("TVXS", "https://tvxs.gr/feed", "https://tvxs.gr", "el", "GR"),
    ("Left.gr", "https://left.gr/feed", "https://left.gr", "el", "GR"),
    ("Avgi", "https://www.avgi.gr/rss.xml", "https://www.avgi.gr", "el", "GR"),
    ("Iskra", "https://iskra.gr/feed/", "https://iskra.gr", "el", "GR"),

    # ── Austria & Switzerland ─────────────────────────────────────────────
    ("Mosaik Blog", "https://mosaik-blog.at/feed/", "https://mosaik-blog.at", "de", "AT"),
    ("Augustin", "https://augustin.or.at/feed/", "https://augustin.or.at", "de", "AT"),
    ("WOZ Die Wochenzeitung", "https://www.woz.ch/feed", "https://www.woz.ch", "de", "CH"),
    ("Vorwärts CH", "https://www.vorwaerts.ch/feed/", "https://www.vorwaerts.ch", "de", "CH"),

    # ── Eastern Europe ───────────────────────────────────────────────────
    ("Krytyka Polityczna", "https://kfrytyka.com/feed/", "https://kfrytyka.com", "pl", "PL"),
    ("Strajk", "https://strajk.eu/feed/", "https://strajk.eu", "pl", "PL"),
    ("Le Monde Diplomatique PL", "https://monde-diplomatique.pl/feed/", "https://monde-diplomatique.pl", "pl", "PL"),
    ("A2larm", "https://a2larm.cz/feed/", "https://a2larm.cz", "cs", "CZ"),
    ("Deník Referendum", "https://denikreferendum.cz/rss", "https://denikreferendum.cz", "cs", "CZ"),
    ("Mérce", "https://merce.hu/feed/", "https://merce.hu", "hu", "HU"),
    ("Szabad Európa", "https://www.szabadeuropa.hu/api/feed", "https://www.szabadeuropa.hu", "hu", "HU"),
    ("Bilten", "https://www.bilten.org/feed/", "https://www.bilten.org", "hr", "HR"),
    ("Novosti", "https://www.portalnovosti.com/rss", "https://www.portalnovosti.com", "hr", "HR"),
    ("Peščanik", "https://pescanik.net/feed/", "https://pescanik.net", "sr", "RS"),
    ("Masina", "https://www.masina.rs/feed/", "https://www.masina.rs", "sr", "RS"),
    ("LeftEast", "https://lefteast.org/feed/", "https://lefteast.org", "en", "RO"),
    ("CriticAtac", "https://www.criticatac.ro/feed/", "https://www.criticatac.ro", "ro", "RO"),
    ("Baricada", "https://baricada.org/feed/", "https://baricada.org", "bg", "BG"),

    # ── Turkey ───────────────────────────────────────────────────────────
    ("BirGün", "https://www.birgun.net/rss", "https://www.birgun.net", "tr", "TR"),
    ("Evrensel", "https://www.evrensel.net/rss/haber.xml", "https://www.evrensel.net", "tr", "TR"),
    ("Sol Haber", "https://sol.org.tr/rss", "https://sol.org.tr", "tr", "TR"),
    ("Gazete Duvar", "https://www.gazeteduvar.com.tr/rss/anasayfa.xml", "https://www.gazeteduvar.com.tr", "tr", "TR"),
    ("Sendika.Org", "https://sendika.org/feed/", "https://sendika.org", "tr", "TR"),

    # ── Latin America ────────────────────────────────────────────────────
    ("TeleSUR", "https://www.telesurenglish.net/rss/all.xml", "https://www.telesurenglish.net", "en", "VE"),
    ("TeleSUR ES", "https://www.telesurtv.net/rss/all.xml", "https://www.telesurtv.net", "es", "VE"),
    ("Página/12", "https://www.pagina12.com.ar/rss/portada", "https://www.pagina12.com.ar", "es", "AR"),
    ("La Izquierda Diario AR", "https://www.laizquierdadiario.com/feed", "https://www.laizquierdadiario.com", "es", "AR"),
    ("Tiempo Argentino", "https://www.tiempoar.com.ar/feed/", "https://www.tiempoar.com.ar", "es", "AR"),
    ("Resumen Latinoamericano", "https://www.resumenlatinoamericano.org/feed/", "https://www.resumenlatinoamericano.org", "es", "AR"),
    ("NACLA", "https://nacla.org/feed/", "https://nacla.org", "en", "US"),
    ("Brasil de Fato", "https://www.brasildefato.com.br/rss2.xml", "https://www.brasildefato.com.br", "pt", "BR"),
    ("Carta Capital", "https://www.cartacapital.com.br/feed/", "https://www.cartacapital.com.br", "pt", "BR"),
    ("The Intercept Brasil", "https://www.intercept.com.br/feed/", "https://www.intercept.com.br", "pt", "BR"),
    ("Esquerda Online BR", "https://esquerdaonline.com.br/feed/", "https://esquerdaonline.com.br", "pt", "BR"),
    ("Mídia Ninja", "https://midianinja.org/feed/", "https://midianinja.org", "pt", "BR"),
    ("Opera Mundi", "https://operamundi.uol.com.br/feed/", "https://operamundi.uol.com.br", "pt", "BR"),
    ("Agência Pública", "https://apublica.org/feed/", "https://apublica.org", "pt", "BR"),
    ("La Jornada", "https://www.jornada.com.mx/rss/edicion.xml", "https://www.jornada.com.mx", "es", "MX"),
    ("Pie de Página", "https://piedepagina.mx/feed/", "https://piedepagina.mx", "es", "MX"),
    ("Desinformémonos", "https://desinformemonos.org/feed/", "https://desinformemonos.org", "es", "MX"),
    ("Proceso", "https://www.proceso.com.mx/feed/", "https://www.proceso.com.mx", "es", "MX"),
    ("CIPER Chile", "https://www.ciperchile.cl/feed/", "https://www.ciperchile.cl", "es", "CL"),
    ("El Desconcierto", "https://www.eldesconcierto.cl/feed/", "https://www.eldesconcierto.cl", "es", "CL"),
    ("The Clinic", "https://www.theclinic.cl/feed/", "https://www.theclinic.cl", "es", "CL"),
    ("Interferencia", "https://interferencia.cl/feed", "https://interferencia.cl", "es", "CL"),
    ("Colombia Informa", "https://www.colombiainforma.info/feed/", "https://www.colombiainforma.info", "es", "CO"),
    ("Contagio Radio", "https://www.contagioradio.com/feed/", "https://www.contagioradio.com", "es", "CO"),
    ("Wambra", "https://wambra.ec/feed/", "https://wambra.ec", "es", "EC"),
    ("La Diaria", "https://ladiaria.com.uy/rss/", "https://ladiaria.com.uy", "es", "UY"),
    ("Última Hora", "https://www.ultimahora.com/rss", "https://www.ultimahora.com", "es", "PY"),
    ("Cubadebate", "https://www.cubadebate.cu/feed/", "https://www.cubadebate.cu", "es", "CU"),
    ("Granma", "https://www.granma.cu/feed", "https://www.granma.cu", "es", "CU"),
    ("Prensa Latina", "https://www.plenglish.com/feed/", "https://www.plenglish.com", "en", "CU"),
    ("OnCuba News", "https://oncubanews.com/feed/", "https://oncubanews.com", "es", "CU"),

    # ── India & South Asia ───────────────────────────────────────────────
    ("The Wire", "https://thewire.in/feed", "https://thewire.in", "en", "IN"),
    ("Scroll.in", "https://scroll.in/feed", "https://scroll.in", "en", "IN"),
    ("Newsclick", "https://www.newsclick.in/rss.xml", "https://www.newsclick.in", "en", "IN"),
    ("People's Democracy", "https://peoplesdemocracy.in/feed", "https://peoplesdemocracy.in", "en", "IN"),
    ("Frontline", "https://frontline.thehindu.com/feed/", "https://frontline.thehindu.com", "en", "IN"),
    ("The Caravan", "https://caravanmagazine.in/feed", "https://caravanmagazine.in", "en", "IN"),
    ("Peoples Dispatch", "https://peoplesdispatch.org/feed/", "https://peoplesdispatch.org", "en", "IN"),
    ("Counter Currents", "https://countercurrents.org/feed/", "https://countercurrents.org", "en", "IN"),
    ("National Herald India", "https://www.nationalheraldindia.com/rss", "https://www.nationalheraldindia.com", "en", "IN"),
    ("The News International", "https://www.thenews.com.pk/rss/1/1", "https://www.thenews.com.pk", "en", "PK"),
    ("Himal Southasian", "https://www.himalmag.com/feed/", "https://www.himalmag.com", "en", "NP"),
    ("Kathmandu Post", "https://kathmandupost.com/rss", "https://kathmandupost.com", "en", "NP"),

    # ── Southeast Asia ───────────────────────────────────────────────────
    ("New Mandala", "https://www.newmandala.org/feed/", "https://www.newmandala.org", "en", "AU"),
    ("Prachatai English", "https://prachatai.com/english/feed", "https://prachatai.com/english", "en", "TH"),
    ("Rappler", "https://www.rappler.com/feed/", "https://www.rappler.com", "en", "PH"),
    ("Bulatlat", "https://www.bulatlat.com/feed/", "https://www.bulatlat.com", "en", "PH"),
    ("New Naratif", "https://newnaratif.com/feed/", "https://newnaratif.com", "en", "SG"),
    ("Malaysiakini", "https://www.malaysiakini.com/rss/en/news", "https://www.malaysiakini.com", "en", "MY"),
    ("Tempo.co", "https://rss.tempo.co/nasional", "https://www.tempo.co", "id", "ID"),
    ("Tirto.id", "https://tirto.id/feed/", "https://tirto.id", "id", "ID"),

    # ── East Asia ────────────────────────────────────────────────────────
    ("Hankyoreh", "https://english.hani.co.kr/rss/", "https://english.hani.co.kr", "en", "KR"),
    ("Pressian", "https://www.pressian.com/rss/all.xml", "https://www.pressian.com", "ko", "KR"),
    ("Ohmynews", "https://www.ohmynews.com/rss/", "https://www.ohmynews.com", "ko", "KR"),
    ("Asahi Shimbun", "https://www.asahi.com/rss/asahi/newsheadlines.rdf", "https://www.asahi.com", "ja", "JP"),
    ("Akahata", "https://www.jcp.or.jp/akahata/aik_index/rss.xml", "https://www.jcp.or.jp/akahata", "ja", "JP"),
    ("Labor Net Japan", "https://www.labornetjp.org/feed", "https://www.labornetjp.org", "ja", "JP"),
    ("Initium Media", "https://theinitium.com/feed", "https://theinitium.com", "zh", "HK"),
    ("Stand News Archive", "https://www.thestandnews.com/rss", "https://www.thestandnews.com", "zh", "HK"),
    ("New Bloom", "https://newbloommag.net/feed/", "https://newbloommag.net", "en", "TW"),

    # ── Middle East & North Africa ────────────────────────────────────────
    ("Middle East Eye", "https://www.middleeasteye.net/rss", "https://www.middleeasteye.net", "en", "UK"),
    ("Al-Monitor", "https://www.al-monitor.com/rss", "https://www.al-monitor.com", "en", "US"),
    ("Haaretz", "https://www.haaretz.com/cmlink/1.628752", "https://www.haaretz.com", "en", "IL"),
    ("+972 Magazine", "https://www.972mag.com/feed/", "https://www.972mag.com", "en", "IL"),
    ("Local Call", "https://www.localcall.co.il/feed/", "https://www.localcall.co.il", "he", "IL"),
    ("Al-Akhbar", "https://al-akhbar.com/rss", "https://al-akhbar.com", "ar", "LB"),
    ("Al Jazeera English", "https://www.aljazeera.com/xml/rss/all.xml", "https://www.aljazeera.com", "en", "QA"),
    ("The New Arab", "https://www.newarab.com/rss", "https://www.newarab.com", "en", "UK"),
    ("Orient XXI", "https://orientxxi.info/spip.php?page=backend", "https://orientxxi.info", "fr", "FR"),
    ("Mada Masr", "https://www.madamasr.com/en/feed/", "https://www.madamasr.com", "en", "EG"),
    ("Nawaat", "https://nawaat.org/feed/", "https://nawaat.org", "ar", "TN"),
    ("Lakome", "https://lakome2.com/feed/", "https://lakome2.com", "ar", "MA"),

    # ── Sub-Saharan Africa ───────────────────────────────────────────────
    ("Daily Maverick", "https://www.dailymaverick.co.za/rss/", "https://www.dailymaverick.co.za", "en", "ZA"),
    ("New Frame", "https://www.newframe.com/feed/", "https://www.newframe.com", "en", "ZA"),
    ("GroundUp", "https://www.groundup.org.za/feeds/articles/", "https://www.groundup.org.za", "en", "ZA"),
    ("Amandla!", "https://aidc.org.za/feed/", "https://aidc.org.za", "en", "ZA"),
    ("The Continent", "https://www.thecontinent.org/feed/", "https://www.thecontinent.org", "en", "ZA"),
    ("African Arguments", "https://africanarguments.org/feed/", "https://africanarguments.org", "en", "UK"),
    ("Pambazuka News", "https://www.pambazuka.org/rss.xml", "https://www.pambazuka.org", "en", "KE"),
    ("The Elephant", "https://www.theelephant.info/feed/", "https://www.theelephant.info", "en", "KE"),
    ("Chimurenga", "https://chimurengachronic.co.za/feed/", "https://chimurengachronic.co.za", "en", "ZA"),
    ("Mail & Guardian", "https://mg.co.za/feed/", "https://mg.co.za", "en", "ZA"),
    ("Premium Times Nigeria", "https://www.premiumtimesng.com/feed", "https://www.premiumtimesng.com", "en", "NG"),
    ("Sahara Reporters", "https://saharareporters.com/feed", "https://saharareporters.com", "en", "NG"),
    ("The East African", "https://www.theeastafrican.co.ke/rss", "https://www.theeastafrican.co.ke", "en", "KE"),
    ("Addis Standard", "https://addisstandard.com/feed/", "https://addisstandard.com", "en", "ET"),

    # ── Australia & New Zealand ──────────────────────────────────────────
    ("New Matilda", "https://newmatilda.com/feed/", "https://newmatilda.com", "en", "AU"),
    ("Green Left", "https://www.greenleft.org.au/rss.xml", "https://www.greenleft.org.au", "en", "AU"),
    ("Overland", "https://overland.org.au/feed/", "https://overland.org.au", "en", "AU"),
    ("Red Flag", "https://redflag.org.au/feed/", "https://redflag.org.au", "en", "AU"),
    ("The Saturday Paper", "https://www.thesaturdaypaper.com.au/rss", "https://www.thesaturdaypaper.com.au", "en", "AU"),
    ("Crikey", "https://www.crikey.com.au/feed/", "https://www.crikey.com.au", "en", "AU"),
    ("Michael West Media", "https://www.michaelwest.com.au/feed/", "https://www.michaelwest.com.au", "en", "AU"),
    ("The Conversation AU", "https://theconversation.com/au/articles.atom", "https://theconversation.com/au", "en", "AU"),
    ("Pearls and Irritations", "https://johnmenadue.com/feed/", "https://johnmenadue.com", "en", "AU"),
    ("The Daily Blog NZ", "https://thedailyblog.co.nz/feed/", "https://thedailyblog.co.nz", "en", "NZ"),
    ("The Spinoff", "https://thespinoff.co.nz/feed", "https://thespinoff.co.nz", "en", "NZ"),

    # ── Canada ───────────────────────────────────────────────────────────
    ("The Tyee", "https://thetyee.ca/rss2.xml", "https://thetyee.ca", "en", "CA"),
    ("Rabble.ca", "https://rabble.ca/feed/", "https://rabble.ca", "en", "CA"),
    ("The Breach", "https://breachmedia.ca/feed/", "https://breachmedia.ca", "en", "CA"),
    ("Canadian Dimension", "https://canadiandimension.com/feed/", "https://canadiandimension.com", "en", "CA"),
    ("PressProgress", "https://pressprogress.ca/feed/", "https://pressprogress.ca", "en", "CA"),
    ("The Narwhal", "https://thenarwhal.ca/feed/", "https://thenarwhal.ca", "en", "CA"),
    ("National Observer", "https://www.nationalobserver.com/feed", "https://www.nationalobserver.com", "en", "CA"),
    ("Spring Magazine", "https://springmag.ca/feed/", "https://springmag.ca", "en", "CA"),
    ("Briarpatch", "https://briarpatchmagazine.com/feed/", "https://briarpatchmagazine.com", "en", "CA"),

    # ── International / Multi-region ─────────────────────────────────────
    ("Jacobin", "https://jacobin.com/feed/", "https://jacobin.com", "en", "INT"),
    ("Monthly Review", "https://monthlyreview.org/feed/", "https://monthlyreview.org", "en", "INT"),
    ("New Internationalist", "https://newint.org/feed", "https://newint.org", "en", "INT"),
    ("Red Pepper (INT)", "https://www.redpepper.org.uk/feed/", "https://www.redpepper.org.uk", "en", "INT"),
    ("Rosa Luxemburg Stiftung", "https://www.rosalux.de/feed/", "https://www.rosalux.de", "de", "INT"),
    ("Transform Europe", "https://www.transform-network.net/feed/", "https://www.transform-network.net", "en", "INT"),
    ("Verso Books Blog", "https://www.versobooks.com/blogs/feed", "https://www.versobooks.com/blogs", "en", "INT"),
    ("Haymarket Books", "https://www.haymarketbooks.org/blogs/feed", "https://www.haymarketbooks.org", "en", "INT"),
    ("Links International", "https://links.org.au/rss.xml", "https://links.org.au", "en", "INT"),
    ("International Viewpoint", "https://internationalviewpoint.org/spip.php?page=backend", "https://internationalviewpoint.org", "en", "INT"),
    ("Marxist.com", "https://www.marxist.com/feed", "https://www.marxist.com", "en", "INT"),
    ("Liberation School", "https://www.liberationschool.org/feed/", "https://www.liberationschool.org", "en", "INT"),
    ("Socialist Project", "https://www.socialistproject.ca/feed/", "https://www.socialistproject.ca", "en", "INT"),
    ("World Socialist Website", "https://www.wsws.org/en/rss.xml", "https://www.wsws.org", "en", "INT"),
    ("Anti-War.com", "https://news.antiwar.com/feed/", "https://news.antiwar.com", "en", "INT"),
    ("Consortium News", "https://consortiumnews.com/feed/", "https://consortiumnews.com", "en", "INT"),
    ("MintPress News", "https://www.mintpressnews.com/feed/", "https://www.mintpressnews.com", "en", "INT"),
    ("The Grayzone", "https://thegrayzone.com/feed/", "https://thegrayzone.com", "en", "INT"),
    ("Globalization Monitor", "https://www.globalmon.org.hk/feed/", "https://www.globalmon.org.hk", "en", "INT"),

    # ── Additional Global Sources ────────────────────────────────────────
    ("Equal Times", "https://www.equaltimes.org/feed", "https://www.equaltimes.org", "en", "INT"),
    ("IPS News", "https://www.ipsnews.net/feed/", "https://www.ipsnews.net", "en", "INT"),
    ("Global Voices", "https://globalvoices.org/feed/", "https://globalvoices.org", "en", "INT"),
    ("Open Global Rights", "https://www.openglobalrights.org/feed/", "https://www.openglobalrights.org", "en", "INT"),
    ("Waging Nonviolence", "https://wagingnonviolence.org/feed/", "https://wagingnonviolence.org", "en", "INT"),
    ("ZNet / ZComm", "https://znetwork.org/feed/", "https://znetwork.org", "en", "INT"),
    ("The Bullet", "https://socialistproject.ca/bullet/feed/", "https://socialistproject.ca/bullet/", "en", "INT"),
    ("Climate & Capitalism", "https://climateandcapitalism.com/feed/", "https://climateandcapitalism.com", "en", "INT"),
    ("Africa Is a Country", "https://africasacountry.com/feed", "https://africasacountry.com", "en", "INT"),
    ("Developing Economics", "https://developingeconomics.org/feed/", "https://developingeconomics.org", "en", "INT"),
    ("Phenotype", "https://phenotype.press/feed/", "https://phenotype.press", "en", "INT"),
    ("UnHerd (left voices)", "https://unherd.com/feed/", "https://unherd.com", "en", "UK"),
    ("Declassified UK", "https://declassifieduk.org/feed/", "https://declassifieduk.org", "en", "UK"),
    ("Double Down News", "https://www.doubledown.news/feed/", "https://www.doubledown.news", "en", "UK"),
    ("Responsible Statecraft", "https://responsiblestatecraft.org/feed/", "https://responsiblestatecraft.org", "en", "US"),
    ("Foreign Policy in Focus", "https://fpif.org/feed/", "https://fpif.org", "en", "US"),
    ("The Diplomat", "https://thediplomat.com/feed/", "https://thediplomat.com", "en", "INT"),
    ("Inkstick Media", "https://inkstickmedia.com/feed/", "https://inkstickmedia.com", "en", "US"),
    ("Defector", "https://defector.com/feed/rss", "https://defector.com", "en", "US"),
    ("Hell Gate", "https://hellgatenyc.com/rss/", "https://hellgatenyc.com", "en", "US"),
    ("The Lever News", "https://www.levernews.com/rss/", "https://www.levernews.com", "en", "US"),
    ("Drop Site News", "https://www.dropsitenews.com/feed", "https://www.dropsitenews.com", "en", "US"),
    ("Zeteo", "https://zeteo.com/feed", "https://zeteo.com", "en", "US"),

    # ── Additional Latin America ─────────────────────────────────────────
    ("La Tinta", "https://latinta.com.ar/feed/", "https://latinta.com.ar", "es", "AR"),
    ("Marcha Noticias", "https://www.marcha.org.ar/feed/", "https://www.marcha.org.ar", "es", "AR"),
    ("ANRed", "https://www.anred.org/feed/", "https://www.anred.org", "es", "AR"),
    ("Periódico Diagonal", "https://www.diagonalperiodico.net/feed", "https://www.diagonalperiodico.net", "es", "ES"),
    ("Correo del Alba", "https://www.correodelalba.org/feed/", "https://www.correodelalba.org", "es", "VE"),
    ("Orinoco Tribune", "https://orinocotribune.com/feed/", "https://orinocotribune.com", "en", "VE"),

    # ── Additional Europe ────────────────────────────────────────────────
    ("Mediapart English", "https://www.mediapart.fr/en/articles/feed", "https://www.mediapart.fr/en", "en", "FR"),
    ("Le Monde Diplo English", "https://mondediplo.com/backend", "https://mondediplo.com", "en", "FR"),
    ("Il Post", "https://www.ilpost.it/feed/", "https://www.ilpost.it", "it", "IT"),
    ("Fanpage.it", "https://www.fanpage.it/feed/", "https://www.fanpage.it", "it", "IT"),
    ("Lutte Ouvrière", "https://www.lutte-ouvriere.org/rss.xml", "https://www.lutte-ouvriere.org", "fr", "FR"),
    ("Viento Sur", "https://vientosur.info/feed/", "https://vientosur.info", "es", "ES"),
    ("Sin Permiso", "https://www.sinpermiso.info/rss.xml", "https://www.sinpermiso.info", "es", "ES"),

    # ── Additional Asia/Pacific ──────────────────────────────────────────
    ("Asia Times", "https://asiatimes.com/feed/", "https://asiatimes.com", "en", "HK"),
    ("The Diplomat", "https://thediplomat.com/feed/", "https://thediplomat.com", "en", "INT"),
    ("Nikkei Asia (opinion)", "https://asia.nikkei.com/rss", "https://asia.nikkei.com", "en", "JP"),
    ("Jakarta Post", "https://www.thejakartapost.com/rss", "https://www.thejakartapost.com", "en", "ID"),
    ("Dawn", "https://www.dawn.com/feeds/home", "https://www.dawn.com", "en", "PK"),
    ("The Daily Star BD", "https://www.thedailystar.net/rss", "https://www.thedailystar.net", "en", "BD"),
    ("Khabar Lahariya", "https://khabarlahariya.org/feed/", "https://khabarlahariya.org", "en", "IN"),
    ("NewsLaundry", "https://www.newslaundry.com/feed", "https://www.newslaundry.com", "en", "IN"),

    # ── Additional Africa ────────────────────────────────────────────────
    ("Amandla! Magazine", "https://aidc.org.za/amandla/feed/", "https://aidc.org.za/amandla/", "en", "ZA"),
    ("Open Society Foundations", "https://www.opensocietyfoundations.org/rss", "https://www.opensocietyfoundations.org", "en", "INT"),
    ("ROAPE", "https://roape.net/feed/", "https://roape.net", "en", "INT"),
    ("Africa Confidential", "https://www.africa-confidential.com/rss", "https://www.africa-confidential.com", "en", "UK"),
    ("The Republic", "https://republic.com.ng/feed/", "https://republic.com.ng", "en", "NG"),
    ("This Is Africa", "https://thisisafrica.me/feed/", "https://thisisafrica.me", "en", "INT"),

    # ── Additional Middle East ───────────────────────────────────────────
    ("Al Jazeera Arabic", "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9", "https://www.aljazeera.net", "ar", "QA"),
    ("Middle East Monitor", "https://www.middleeastmonitor.com/feed/", "https://www.middleeastmonitor.com", "en", "UK"),
    ("Jadaliyya", "https://www.jadaliyya.com/rss", "https://www.jadaliyya.com", "en", "INT"),
    ("Al-Araby (EN)", "https://www.alaraby.co.uk/english/rss", "https://www.alaraby.co.uk", "en", "UK"),
    ("Raseef22", "https://raseef22.net/feed", "https://raseef22.net", "ar", "LB"),

    # ── Russia & post-Soviet (independent/left) ─────────────────────────
    ("Meduza", "https://meduza.io/rss/all", "https://meduza.io", "ru", "LV"),
    ("Novaya Gazeta Europe", "https://novayagazeta.eu/rss", "https://novayagazeta.eu", "ru", "LV"),
    ("OVD-Info", "https://ovd.info/rss.xml", "https://ovd.info", "ru", "RU"),
    ("Posle", "https://posle.media/feed/", "https://posle.media", "ru", "RU"),
]

SOURCE_COUNT = len(SOURCES)
